package problems;

public class Problem2 {
	/**
	 * Even Fibonacci numbers
	 * 
	 * Each new term in the Fibonacci sequence is generated by adding the
	 * previous two terms. By starting with 1 and 2, the first 10 terms will be:
	 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ... By considering the terms in the
	 * Fibonacci sequence whose values do not exceed four million, find the sum
	 * of the even-valued terms.
	 **/
	public static long solution() {
		long answer = 0, lastValue = 0, actualValue = 1;
		while (actualValue <= 4000000) {
			long temp = actualValue;
			actualValue = actualValue + lastValue;
			lastValue = temp;
			if (actualValue % 2 == 0)
				answer += actualValue;
		}

		return answer;
	}
}
